apiVersion: v1
kind: DeploymentConfig
metadata:
  name: secured-vertx-rest
spec:
  replicas: 1
  selector:
    project: secured-vertx-rest
    provider: fabric8
    group: org.jboss.quickstart
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      labels:
        provider: fabric8
        project: secured-vertx-rest
        version: 1.0-SNAPSHOT
        group: org.jboss.quickstart
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_DIR
          value: /deployments
        - name: SSO_URL
          value: 'https://secure-sso-sso.e8ca.engint.openshiftapps.com/auth'
        - name: REALM
          value: 'master'
        - name: REALM_PUBLIC_KEY
          value: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjSLQrbpwNkpuNc+LxcrG711/oIsqUshISLWjXALgx6/L7NItNrPjJTwzqtWCTJrl0/eQLcPdi7UeZA1qjPGa1l+AIj+FnLyCOl7gm65xB3xUpRuGNe5mJ9a+ZtzprXOKhd0WRC8ydiMwyFxIQJPjt7ywlNvU0hZR1U3QboLRICadP5WPaoYNOaYmpkX34r+kegVfdga+1xqG6Ba5v2/9rRg74KxJubCQxcinbH7gVIYSyFQPP5OpBo14SuynFL1YhWDpgUhLz7gr60sG+RC5eC0zuvCRTELn+JquSogPUopuDej/Sd3T5VYHIBJ8P4x4MIz9/FDX8bOFwM73nHgL5wIDAQAB'
        - name: CLIENT_ID
          value: 'demoapp'
        - name: SECRET
          value: 'cb7a8528-ad53-4b2e-afb8-72e9795c27c8'
        image: secured-vertx-rest:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        name: secured-vertx-rest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - secured-vertx-rest
      from:
        kind: ImageStreamTag
        name: secured-vertx-rest:latest
    type: ImageChange
